services:
  - type: web
    name: social-app-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SERVER_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
